### ISSUE TITLE
Missing & undocumented vehicleType value in Stop elements

### ISSUE THREAD

**Issue by PasiSalenius** [HSLdevcom/digitransit#105]
The following example Stop element returned by a graphQL query contains a vehicleType value, which is undocumented in Digitransit developer documentation.  It also has a "missing" value of -999 for a large portion of MATKA stops.

Will there be any improvement to this?

```
"stop": {
	"gtfsId": "MATKA:3_2029",
	"name": "Pispalanharju 19",
	"lat": 61.501502,
	"lon": 23.717554,
	"vehicleType": -999,
	"routes": [],
	"desc": null,
	"code": null
}
```

**Comment by tuukka** [comment]
`vehicle_type` is an optional field in the GTFS stops.txt file, similar to `route_type` in routes.txt. The field is missing from the Matka.fi data, so I'd expect every MATKA stop to have the "missing" value. I suggest using the modes of the routes of the patterns of the stops instead.

**Comment by PasiSalenius** [comment]
Okay, will do that. Was just waiting for a possible fix here before release.
