### ISSUE TITLE
Pelias search must better support partial matches

### ISSUE THREAD

**Issue by mhalttu** [HSLdevcom/digitransit#111]
This request https://api.digitransit.fi/geocoding/v1/search?text=loistepu returns the address "Loisteputki" which can be found in Helsinki. 

This request https://api.digitransit.fi/geocoding/v1/search?text=loistep does not.

As long as the autocomplete requests have severe limitations (see https://github.com/HSLdevcom/digitransit/issues/109 and https://github.com/HSLdevcom/digitransit/issues/110) Pelias search should return valid results from partial matches as long as there is a reasonable amount of letters in the query (e.g. more than 3)

**Comment by vesameskanen** [comment]
Confirmed. Search is currently optimized for full search strings. Anyway, Digitransit itself uses it for partial searches, so we will improve scoring of partial matches.

**Comment by vesameskanen** [comment]
Fixed by; https://github.com/HSLdevcom/pelias-api/pull/42 

The fix will be deployed during 1st half of February.

**Comment by vesameskanen** [comment]
Fix deployed, time to close the issue.
