### ISSUE TITLE
Error 500 when searching for "capell"

### ISSUE THREAD

**Issue by mhalttu** [HSLdevcom/digitransit#113]
https://api.digitransit.fi/geocoding/v1/search?text=capell&size=40&focus.point.lat=60.171905&focus.point.lon=24.94140&lang=en

{"error":"Cannot read property '0' of undefined"}

**Comment by vesameskanen** [comment]
Confirmed.

**Comment by vesameskanen** [comment]
Fixed by: 
https://github.com/HSLdevcom/pelias-api/pull/43
