### ISSUE TITLE
Unify repository usage

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/digitransit#79]
All our code is not under HSLDevCom. We should fix this.

- Check common.yaml file under digitransit-deploy project and move all required repositories under hsldevcom
- Check digitransit-geocoder Dockerfile and fork all used repositories under tpievila to hsldevcom
- Check route server dependencies

**Comment by tpievila** [comment]
https://github.com/tpievila/imposm-parser needs to be transferred to hsldevcom

**Comment by tuukka** [comment]
@tpievila done
